[agent]
    interval = "1ms"
    flush_interval = "250ms"
    round_interval = true
    omit_hostname = true

[[inputs.socket_listener]]
    service_address = "tcp://:8094"
    data_format = "influx"

# [[inputs.mqtt_consumer]]
#     servers = ["tcp://172.30.0.1:1883"]
#     username = "sunride"
#     password = "launchbox"
#     topics = ["test/#"]
#     data_format = "influx"
#     data_type = "int"
#     name_override = "position"



[[outputs.influxdb_v2]]
    urls = ["http://influxdb:8086"]
    token = "${INFLUX_TOKEN}"
    organization = "sunride"
    bucket = "telegraf"
    flush_interval = "1s"

# [[aggregators.basicstats]]
#     period = "100ms"
#     stats = ["mean"]
#     namepass = ["pressures"]

# [[outputs.websocket]]
#   url = "ws://grafana:3000/api/live/push/pressures"
#   data_format = "influx"
#   [outputs.websocket.headers]
#     Authorization = "${GRAFANA_TOKEN_STRING}"

    


